-- CLIENTES
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Sr. Isaque Novaes', 'Santos', '2025-12-26');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Thiago da Cruz', 'Viana', '2026-03-30');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('João Felipe Cirino', 'Rios Verde', '2026-05-14');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Valentina Moura', 'Cardoso', '2024-12-01');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Hellena Guerra', 'Carvalho', '2025-07-28');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Manuella Fogaça', 'Azevedo do Galho', '2025-07-20');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Erick Gonçalves', 'Barbosa da Serra', '2025-05-29');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Stephany Peixoto', 'Pereira de Pinto', '2026-05-10');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Maria Fernanda da Cruz', 'Barbosa da Serra', '2025-05-21');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Sophia Teixeira', 'Mendes', '2025-12-17');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('João Azevedo', 'Monteiro', '2024-09-03');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Sra. Beatriz Rios', 'Marques', '2024-09-23');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Joana das Neves', 'Melo', '2025-02-01');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Mirella Duarte', 'Castro de Goiás', '2026-07-16');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Marcela Pires', 'Jesus de da Conceição', '2024-11-29');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Rebeca da Cunha', 'Barbosa', '2024-09-13');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Henrique Gonçalves', 'Alves das Flores', '2024-12-14');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Eduardo Peixoto', 'da Rocha de Sousa', '2024-09-30');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Maysa da Cunha', 'Nunes', '2026-03-02');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Francisco Carvalho', 'Peixoto de Abreu', '2024-10-22');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Marcos Vinicius Pereira', 'Barros Alegre', '2026-08-05');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Letícia Lima', 'Siqueira', '2026-02-20');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Daniela Freitas', 'Souza', '2026-03-27');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Isadora Barros', 'da Cruz do Campo', '2025-08-24');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Benjamim Mendes', 'Gonçalves', '2025-02-02');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('João Gabriel da Cruz', 'Martins de Mendes', '2025-02-08');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Yan Vasconcelos', 'Barros', '2024-10-24');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Luan Monteiro', 'Moraes', '2025-08-05');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Dra. Julia Viana', 'Leão', '2025-09-30');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Ravi Cassiano', 'da Cunha', '2024-12-22');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Beatriz Cavalcanti', 'Barros de Barbosa', '2024-09-10');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Diogo Gomes', 'Albuquerque do Galho', '2025-08-07');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Noah Garcia', 'Barbosa', '2024-12-10');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Sofia Sá', 'Sá de Sousa', '2026-07-29');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Brenda Ribeiro', 'Silva Paulista', '2024-11-12');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Luiz Fernando Sá', 'Azevedo de Sampaio', '2025-06-22');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Alexandre da Cunha', 'Almeida da Prata', '2025-09-13');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Isaque Siqueira', 'Aragão', '2026-05-03');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Ana Oliveira', 'Brito Alegre', '2026-05-24');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Luiz Otávio Lima', 'Montenegro', '2026-05-23');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Beatriz Borges', 'Duarte do Oeste', '2025-09-07');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Sr. Vitor Jesus', 'Dias da Prata', '2024-11-23');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Maria Vitória Silveira', 'Casa Grande de Minas', '2026-06-11');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Luísa Siqueira', 'da Costa de Minas', '2025-07-11');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Sr. Ian Cirino', 'Cardoso do Norte', '2025-05-21');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('José Miguel Sá', 'Garcia de Minas', '2026-07-24');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Isaque Abreu', 'Moura dos Dourados', '2026-04-05');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Liam Marques', 'Aparecida do Amparo', '2025-03-10');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Maysa Nunes', 'Barbosa', '2025-06-08');
INSERT INTO clientes (nome, cidade, data_cadastro) VALUES ('Vitória Vargas', 'da Mata Paulista', '2025-03-29');

-- PRODUTOS
INSERT INTO produtos (nome_prod, categoria_prod, preco_prod) VALUES ('Nihil Tempora', 'Beleza', 180.33);
INSERT INTO produtos (nome_prod, categoria_prod, preco_prod) VALUES ('Animi Dolor', 'Beleza', 423.42);
INSERT INTO produtos (nome_prod, categoria_prod, preco_prod) VALUES ('Alias Dolorum', 'Roupas', 222.21);
INSERT INTO produtos (nome_prod, categoria_prod, preco_prod) VALUES ('Nisi Quas', 'Eletronicos', 1019.9);
INSERT INTO produtos (nome_prod, categoria_prod, preco_prod) VALUES ('Facilis Dolore', 'Livros', 144.1);
INSERT INTO produtos (nome_prod, categoria_prod, preco_prod) VALUES ('Fugiat Delectus', 'Esportes', 62.2);
INSERT INTO produtos (nome_prod, categoria_prod, preco_prod) VALUES ('Voluptates In', 'Eletronicos', 339.68);
INSERT INTO produtos (nome_prod, categoria_prod, preco_prod) VALUES ('Sit In', 'Livros', 909.0);
INSERT INTO produtos (nome_prod, categoria_prod, preco_prod) VALUES ('Quia Voluptatibus', 'Livros', 310.27);
INSERT INTO produtos (nome_prod, categoria_prod, preco_prod) VALUES ('Molestiae Dicta', 'Beleza', 1056.47);
INSERT INTO produtos (nome_prod, categoria_prod, preco_prod) VALUES ('Repellat Ullam', 'Esportes', 342.35);
INSERT INTO produtos (nome_prod, categoria_prod, preco_prod) VALUES ('Sequi Quaerat', 'Livros', 428.11);
INSERT INTO produtos (nome_prod, categoria_prod, preco_prod) VALUES ('Suscipit Nemo', 'Eletronicos', 1141.83);
INSERT INTO produtos (nome_prod, categoria_prod, preco_prod) VALUES ('Nisi Harum', 'Roupas', 1051.74);
INSERT INTO produtos (nome_prod, categoria_prod, preco_prod) VALUES ('Magni Quas', 'Casa', 427.64);
INSERT INTO produtos (nome_prod, categoria_prod, preco_prod) VALUES ('Nam Sapiente', 'Roupas', 1436.46);
INSERT INTO produtos (nome_prod, categoria_prod, preco_prod) VALUES ('Aspernatur Earum', 'Casa', 166.78);
INSERT INTO produtos (nome_prod, categoria_prod, preco_prod) VALUES ('Ipsam Nesciunt', 'Esportes', 158.62);
INSERT INTO produtos (nome_prod, categoria_prod, preco_prod) VALUES ('Iste Aperiam', 'Casa', 911.53);
INSERT INTO produtos (nome_prod, categoria_prod, preco_prod) VALUES ('Nobis Soluta', 'Eletronicos', 1098.65);

-- PEDIDOS
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-05-26', 'pendente', 35);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-06-12', 'pendente', 25);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-11-17', 'concluído', 19);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-07-27', 'concluído', 40);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-09-27', 'concluído', 24);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-08-20', 'pendente', 46);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-07-31', 'concluído', 43);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-12-06', 'cancelado', 19);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-11-10', 'concluído', 15);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-07-16', 'concluído', 25);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-08-12', 'concluído', 41);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-09-27', 'concluído', 11);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-09-26', 'concluído', 14);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-02-10', 'cancelado', 45);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-12-08', 'pendente', 42);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-03-28', 'concluído', 41);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-07-06', 'concluído', 47);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-07-22', 'concluído', 30);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-06-12', 'concluído', 41);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-01-27', 'concluído', 15);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-12-20', 'concluído', 50);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-11-02', 'concluído', 15);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-03-21', 'concluído', 21);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-08-15', 'concluído', 5);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-12-27', 'concluído', 37);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-08-12', 'concluído', 21);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-01-12', 'concluído', 32);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-05-15', 'concluído', 42);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-02-07', 'pendente', 17);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-05-20', 'concluído', 48);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-08-23', 'concluído', 17);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-05-28', 'concluído', 28);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-07-21', 'concluído', 26);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-02-10', 'concluído', 9);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-09-21', 'concluído', 6);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-05-09', 'concluído', 8);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-11-09', 'concluído', 11);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-06-22', 'concluído', 28);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-02-26', 'concluído', 25);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-11-29', 'concluído', 30);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-09-08', 'concluído', 36);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-06-08', 'concluído', 1);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-01-08', 'concluído', 8);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-10-17', 'concluído', 35);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-05-22', 'concluído', 50);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-11-28', 'concluído', 8);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-09-24', 'concluído', 11);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-09-04', 'concluído', 47);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-03-25', 'cancelado', 17);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-12-15', 'concluído', 49);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-02-28', 'concluído', 7);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-04-19', 'concluído', 20);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-01-28', 'concluído', 33);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-01-12', 'concluído', 10);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-03-18', 'concluído', 11);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-08-02', 'cancelado', 50);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-02-25', 'concluído', 1);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-03-11', 'pendente', 32);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-05-14', 'concluído', 24);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-06-04', 'concluído', 20);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-06-28', 'concluído', 16);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-04-11', 'pendente', 6);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-06-22', 'concluído', 32);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-12-08', 'concluído', 49);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-08-25', 'pendente', 9);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-09-08', 'cancelado', 31);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-11-12', 'concluído', 11);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-10-08', 'concluído', 39);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-06-09', 'cancelado', 14);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-01-27', 'concluído', 49);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-06-28', 'concluído', 13);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-06-05', 'cancelado', 26);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-05-28', 'concluído', 42);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-12-27', 'concluído', 34);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-05-15', 'concluído', 16);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-12-01', 'pendente', 22);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-02-19', 'concluído', 36);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-06-09', 'pendente', 15);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-11-13', 'concluído', 46);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-07-07', 'pendente', 15);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-09-04', 'concluído', 3);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-05-23', 'concluído', 5);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-12-05', 'concluído', 18);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-12-26', 'concluído', 14);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-03-04', 'cancelado', 47);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-04-18', 'concluído', 37);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-05-06', 'concluído', 16);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-06-14', 'concluído', 27);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-08-14', 'concluído', 7);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-07-01', 'concluído', 23);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-06-13', 'concluído', 30);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-04-05', 'concluído', 4);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-05-07', 'pendente', 42);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-05-25', 'concluído', 26);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-05-24', 'concluído', 7);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-04-17', 'concluído', 13);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-05-17', 'concluído', 9);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-02-28', 'concluído', 18);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-10-04', 'concluído', 5);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-11-12', 'pendente', 36);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-04-08', 'cancelado', 42);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-01-11', 'cancelado', 1);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-03-23', 'concluído', 49);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-03-20', 'concluído', 11);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-12-31', 'concluído', 31);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-01-26', 'cancelado', 26);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-06-16', 'concluído', 11);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-08-05', 'concluído', 25);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-07-27', 'concluído', 30);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-09-20', 'cancelado', 45);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-02-17', 'concluído', 36);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-05-28', 'concluído', 32);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-01-02', 'concluído', 19);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-08-08', 'concluído', 4);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-10-31', 'pendente', 35);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-09-20', 'pendente', 21);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-04-13', 'concluído', 38);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-09-02', 'concluído', 34);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-04-03', 'pendente', 33);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-05-19', 'pendente', 12);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-04-06', 'concluído', 5);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-04-08', 'concluído', 16);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-08-24', 'concluído', 37);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-03-07', 'pendente', 39);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-07-06', 'concluído', 6);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-02-16', 'concluído', 38);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-08-12', 'cancelado', 21);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-11-21', 'concluído', 14);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-01-19', 'concluído', 21);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-05-29', 'pendente', 26);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-06-30', 'concluído', 42);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-03-05', 'cancelado', 21);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-06-28', 'pendente', 5);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-06-24', 'cancelado', 40);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-09-22', 'pendente', 7);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-09-07', 'concluído', 14);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-07-31', 'cancelado', 9);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-08-18', 'concluído', 5);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-01-25', 'concluído', 24);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-11-08', 'concluído', 29);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-07-25', 'concluído', 46);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-02-25', 'concluído', 42);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-10-04', 'concluído', 43);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-09-11', 'cancelado', 20);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-08-27', 'cancelado', 7);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-11-20', 'concluído', 9);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-09-03', 'concluído', 7);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2025-11-25', 'concluído', 10);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-06-10', 'concluído', 39);
INSERT INTO pedidos (data_pedidos, status, cliente_id) VALUES ('2026-04-10', 'concluído', 22);

-- ITENS_PEDIDO
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (1, 17, 1, 166.78);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (1, 16, 1, 1436.46);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (1, 9, 4, 310.27);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (2, 2, 2, 423.42);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (2, 1, 3, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (2, 11, 2, 342.35);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (3, 18, 1, 158.62);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (3, 14, 1, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (3, 20, 2, 1098.65);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (3, 1, 5, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (4, 12, 5, 428.11);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (5, 14, 1, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (5, 5, 3, 144.1);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (6, 2, 2, 423.42);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (6, 12, 1, 428.11);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (6, 7, 3, 339.68);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (7, 20, 2, 1098.65);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (7, 5, 4, 144.1);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (7, 8, 1, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (7, 6, 2, 62.2);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (8, 14, 2, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (8, 8, 1, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (8, 9, 4, 310.27);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (9, 16, 2, 1436.46);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (10, 15, 3, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (10, 12, 2, 428.11);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (11, 1, 4, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (11, 7, 3, 339.68);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (12, 3, 5, 222.21);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (12, 9, 4, 310.27);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (12, 12, 5, 428.11);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (13, 1, 2, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (13, 4, 5, 1019.9);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (13, 9, 3, 310.27);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (14, 4, 5, 1019.9);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (15, 12, 1, 428.11);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (15, 11, 4, 342.35);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (15, 14, 5, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (15, 17, 2, 166.78);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (16, 2, 5, 423.42);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (16, 14, 5, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (16, 1, 2, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (17, 14, 5, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (17, 3, 3, 222.21);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (17, 11, 1, 342.35);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (18, 17, 3, 166.78);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (18, 10, 4, 1056.47);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (18, 14, 3, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (19, 7, 4, 339.68);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (19, 14, 2, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (20, 13, 3, 1141.83);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (20, 18, 3, 158.62);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (20, 1, 2, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (21, 19, 4, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (21, 11, 2, 342.35);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (21, 15, 5, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (21, 18, 4, 158.62);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (22, 3, 5, 222.21);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (22, 10, 5, 1056.47);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (23, 3, 2, 222.21);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (23, 8, 2, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (23, 10, 2, 1056.47);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (24, 2, 2, 423.42);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (25, 20, 5, 1098.65);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (25, 3, 2, 222.21);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (25, 15, 4, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (25, 14, 4, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (26, 8, 4, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (26, 5, 2, 144.1);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (26, 1, 2, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (26, 4, 5, 1019.9);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (27, 2, 4, 423.42);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (27, 18, 2, 158.62);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (27, 8, 4, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (27, 4, 5, 1019.9);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (28, 15, 5, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (28, 17, 4, 166.78);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (28, 14, 2, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (29, 15, 5, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (29, 9, 4, 310.27);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (29, 8, 2, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (29, 19, 3, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (30, 3, 3, 222.21);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (30, 10, 3, 1056.47);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (30, 8, 5, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (30, 9, 1, 310.27);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (31, 5, 4, 144.1);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (31, 8, 2, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (32, 3, 4, 222.21);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (32, 14, 3, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (33, 14, 4, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (33, 2, 5, 423.42);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (33, 7, 1, 339.68);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (33, 20, 5, 1098.65);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (34, 16, 4, 1436.46);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (34, 1, 4, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (34, 12, 5, 428.11);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (34, 10, 5, 1056.47);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (35, 16, 3, 1436.46);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (35, 8, 4, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (36, 1, 2, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (36, 13, 4, 1141.83);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (36, 11, 2, 342.35);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (36, 19, 5, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (37, 13, 5, 1141.83);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (38, 3, 4, 222.21);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (39, 15, 1, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (39, 6, 3, 62.2);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (40, 11, 3, 342.35);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (40, 7, 4, 339.68);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (40, 15, 3, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (40, 20, 4, 1098.65);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (41, 3, 5, 222.21);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (41, 16, 1, 1436.46);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (41, 1, 3, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (42, 3, 1, 222.21);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (42, 2, 2, 423.42);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (43, 1, 2, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (43, 5, 2, 144.1);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (44, 4, 3, 1019.9);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (44, 19, 3, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (44, 7, 2, 339.68);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (44, 15, 5, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (45, 6, 3, 62.2);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (46, 19, 1, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (47, 19, 2, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (47, 13, 1, 1141.83);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (47, 20, 5, 1098.65);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (48, 4, 5, 1019.9);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (48, 10, 1, 1056.47);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (49, 12, 5, 428.11);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (50, 12, 1, 428.11);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (50, 3, 4, 222.21);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (50, 17, 4, 166.78);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (50, 11, 1, 342.35);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (51, 12, 2, 428.11);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (51, 15, 5, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (51, 5, 3, 144.1);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (51, 14, 5, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (52, 15, 2, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (52, 14, 1, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (52, 9, 3, 310.27);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (52, 11, 4, 342.35);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (53, 15, 5, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (53, 19, 4, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (54, 1, 2, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (54, 16, 4, 1436.46);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (54, 11, 2, 342.35);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (55, 9, 5, 310.27);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (55, 11, 3, 342.35);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (55, 20, 5, 1098.65);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (56, 17, 2, 166.78);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (57, 8, 4, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (58, 18, 4, 158.62);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (58, 8, 1, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (58, 16, 1, 1436.46);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (58, 20, 3, 1098.65);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (59, 13, 3, 1141.83);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (59, 8, 5, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (60, 16, 3, 1436.46);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (60, 18, 4, 158.62);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (60, 17, 5, 166.78);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (61, 12, 3, 428.11);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (61, 15, 3, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (61, 9, 2, 310.27);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (62, 7, 3, 339.68);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (63, 18, 2, 158.62);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (64, 7, 3, 339.68);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (64, 16, 5, 1436.46);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (65, 4, 2, 1019.9);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (65, 7, 3, 339.68);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (65, 10, 2, 1056.47);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (66, 1, 3, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (66, 18, 1, 158.62);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (66, 5, 1, 144.1);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (67, 5, 1, 144.1);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (67, 16, 5, 1436.46);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (67, 4, 3, 1019.9);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (68, 16, 1, 1436.46);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (68, 15, 3, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (68, 11, 4, 342.35);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (68, 6, 1, 62.2);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (69, 13, 4, 1141.83);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (70, 19, 1, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (71, 5, 3, 144.1);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (71, 19, 1, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (72, 4, 4, 1019.9);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (72, 18, 5, 158.62);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (73, 17, 4, 166.78);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (73, 13, 4, 1141.83);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (74, 19, 5, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (74, 14, 5, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (74, 10, 1, 1056.47);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (75, 7, 2, 339.68);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (76, 3, 2, 222.21);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (76, 6, 5, 62.2);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (76, 8, 1, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (77, 1, 4, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (77, 14, 5, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (78, 10, 3, 1056.47);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (78, 2, 4, 423.42);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (78, 8, 1, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (78, 20, 2, 1098.65);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (79, 19, 1, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (79, 7, 5, 339.68);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (79, 14, 2, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (80, 9, 1, 310.27);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (80, 5, 1, 144.1);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (81, 10, 3, 1056.47);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (81, 19, 4, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (82, 15, 3, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (83, 9, 4, 310.27);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (83, 17, 1, 166.78);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (83, 18, 5, 158.62);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (83, 16, 1, 1436.46);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (84, 11, 2, 342.35);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (84, 9, 5, 310.27);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (84, 1, 5, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (84, 3, 1, 222.21);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (85, 19, 4, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (85, 2, 5, 423.42);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (85, 6, 4, 62.2);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (86, 6, 4, 62.2);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (86, 19, 1, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (86, 14, 4, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (87, 14, 1, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (87, 11, 2, 342.35);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (87, 19, 3, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (88, 16, 4, 1436.46);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (88, 10, 1, 1056.47);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (88, 13, 3, 1141.83);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (88, 2, 3, 423.42);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (89, 4, 1, 1019.9);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (89, 13, 5, 1141.83);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (89, 17, 4, 166.78);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (90, 2, 5, 423.42);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (90, 7, 4, 339.68);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (90, 17, 4, 166.78);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (90, 12, 1, 428.11);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (91, 9, 2, 310.27);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (91, 18, 3, 158.62);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (92, 16, 2, 1436.46);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (92, 4, 3, 1019.9);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (92, 1, 5, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (92, 8, 1, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (93, 3, 1, 222.21);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (93, 8, 2, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (93, 4, 4, 1019.9);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (93, 15, 3, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (94, 14, 2, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (94, 16, 4, 1436.46);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (94, 19, 5, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (95, 13, 5, 1141.83);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (95, 7, 5, 339.68);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (96, 3, 4, 222.21);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (96, 9, 3, 310.27);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (97, 1, 5, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (97, 10, 5, 1056.47);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (97, 19, 4, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (98, 15, 4, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (98, 18, 3, 158.62);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (99, 18, 4, 158.62);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (99, 20, 3, 1098.65);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (99, 13, 2, 1141.83);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (100, 19, 2, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (100, 13, 4, 1141.83);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (101, 11, 4, 342.35);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (102, 13, 2, 1141.83);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (102, 5, 5, 144.1);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (102, 16, 5, 1436.46);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (102, 2, 3, 423.42);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (103, 15, 1, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (104, 1, 1, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (104, 5, 4, 144.1);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (104, 14, 3, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (104, 19, 3, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (105, 3, 3, 222.21);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (105, 11, 4, 342.35);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (105, 18, 5, 158.62);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (105, 13, 1, 1141.83);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (106, 8, 3, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (107, 3, 1, 222.21);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (107, 14, 1, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (108, 6, 3, 62.2);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (108, 10, 1, 1056.47);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (108, 1, 3, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (108, 2, 3, 423.42);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (109, 14, 5, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (109, 5, 4, 144.1);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (109, 8, 5, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (110, 6, 1, 62.2);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (110, 20, 5, 1098.65);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (111, 20, 2, 1098.65);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (111, 8, 4, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (111, 16, 3, 1436.46);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (111, 5, 4, 144.1);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (112, 1, 5, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (112, 15, 2, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (112, 10, 1, 1056.47);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (113, 12, 3, 428.11);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (113, 19, 4, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (113, 10, 3, 1056.47);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (113, 14, 2, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (114, 16, 5, 1436.46);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (114, 4, 3, 1019.9);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (114, 8, 5, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (114, 13, 3, 1141.83);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (115, 1, 1, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (115, 13, 5, 1141.83);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (115, 9, 1, 310.27);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (116, 10, 2, 1056.47);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (116, 8, 5, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (116, 12, 3, 428.11);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (116, 19, 2, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (117, 2, 3, 423.42);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (118, 2, 1, 423.42);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (118, 19, 3, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (118, 12, 3, 428.11);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (118, 5, 4, 144.1);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (119, 7, 5, 339.68);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (119, 5, 3, 144.1);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (120, 6, 3, 62.2);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (120, 9, 3, 310.27);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (120, 16, 1, 1436.46);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (121, 3, 5, 222.21);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (121, 5, 3, 144.1);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (121, 8, 1, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (121, 13, 4, 1141.83);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (122, 9, 5, 310.27);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (123, 15, 3, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (124, 19, 1, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (124, 13, 2, 1141.83);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (124, 12, 4, 428.11);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (125, 20, 5, 1098.65);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (126, 20, 4, 1098.65);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (126, 8, 3, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (126, 3, 4, 222.21);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (127, 5, 1, 144.1);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (128, 10, 4, 1056.47);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (129, 4, 2, 1019.9);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (130, 13, 3, 1141.83);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (130, 15, 5, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (131, 19, 4, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (131, 5, 5, 144.1);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (131, 14, 4, 1051.74);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (131, 4, 3, 1019.9);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (132, 12, 2, 428.11);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (133, 15, 3, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (133, 8, 5, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (133, 12, 3, 428.11);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (133, 4, 1, 1019.9);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (134, 9, 1, 310.27);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (134, 7, 2, 339.68);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (134, 4, 5, 1019.9);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (134, 15, 1, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (135, 11, 2, 342.35);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (136, 19, 1, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (136, 7, 5, 339.68);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (137, 19, 2, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (137, 7, 3, 339.68);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (138, 20, 3, 1098.65);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (138, 1, 2, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (139, 18, 2, 158.62);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (139, 9, 1, 310.27);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (140, 5, 1, 144.1);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (141, 8, 1, 909.0);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (141, 19, 2, 911.53);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (141, 11, 3, 342.35);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (142, 5, 4, 144.1);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (143, 3, 4, 222.21);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (144, 12, 5, 428.11);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (144, 17, 2, 166.78);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (144, 4, 5, 1019.9);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (144, 15, 1, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (145, 15, 4, 427.64);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (145, 1, 4, 180.33);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (145, 2, 4, 423.42);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (146, 16, 4, 1436.46);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (147, 3, 3, 222.21);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (148, 3, 3, 222.21);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (148, 5, 5, 144.1);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (149, 13, 4, 1141.83);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (149, 17, 5, 166.78);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (149, 10, 5, 1056.47);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (150, 4, 4, 1019.9);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (150, 20, 4, 1098.65);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (150, 18, 2, 158.62);
INSERT INTO itens_pedido (pedido_id, produto_id, quantidade, preco_unitario) VALUES (150, 7, 4, 339.68);