CREATE TABLE clientes (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	CIDADE VARCHAR(100) NOT NULL,
	DATA_CADASTRO DATE NOT NULL
);

CREATE TABLE produtos (
	ID_PROD SERIAL PRIMARY KEY,
	NOME_PROD VARCHAR(100) NOT NULL,	
	CATEGORIA_PROD VARCHAR(100) NOT NULL,
	PRECO_PROD NUMERIC(8,2) NOT NULL
);

CREATE TABLE pedidos (
	ID_PEDIDOS SERIAL PRIMARY KEY,
	DATA_PEDIDOS DATE NOT NULL,
	STATUS VARCHAR(20) NOT NULL CHECK (STATUS IN('pendente', 'concluído', 'cancelado')),
	CLIENTE_ID INT NOT NULL REFERENCES CLIENTES(ID)
);

CREATE TABLE itens_pedido(
	id_item SERIAL PRIMARY KEY,
	pedido_id INT NOT NULL REFERENCES pedidos(id_pedidos),
	produto_id INT NOT NULL REFERENCES produtos(id_prod),
	quantidade INT NOT NULL,
	preco_unitario NUMERIC(8,2) NOT NULL
);